In [31]:
import pandas as pd
import numpy as np

In [90]:
df = pd.read_pickle("btc.pickle")

In [91]:
# df1 = pd.DataFrame(df,index=pd.date_range(start='2013-07-01',end='2019-01-31',  freq='M'),columns=['hashrate','price'])

In [183]:
df2 = df[['price','hashrate']]
df_ewm = pd.DataFrame(df2.ewm(com=.5,min_periods=7).mean(),index=pd.date_range(start='2013-07-01',end='2019-02-01',  freq='M'))
df_pct_change = df_ewm.pct_change()[1:]

In [184]:
# df_pct_change = df1.pct_change()

In [185]:
df_pct_change['price'] = df_pct_change['price'].apply(lambda x:x+1)
df_pct_change['hashrate'] = df_pct_change['hashrate'].apply(lambda x:x+1)



df_pct_change['price_change / hashrate_change'] = df_pct_change['price'] / df_pct_change['hashrate']

In [186]:
df_pct_change

               price  hashrate  price_change / hashrate_change
2013-08-31  1.271932  2.254223                        0.564244
2013-09-30  1.021847  1.864931                        0.547928
2013-10-31  1.584751  3.087456                        0.513287
2013-11-30  5.229783  1.476737                        3.541445
2013-12-31  0.739897  1.847970                        0.400384
2014-01-31  1.088564  1.824254                        0.596717
2014-02-28  0.692920  1.602777                        0.432325
2014-03-31  0.817087  1.328142                        0.615211
2014-04-30  0.953975  1.514007                        0.630099
2014-05-31  1.370002  1.285522                        1.065716
2014-06-30  1.005209  1.534626                        0.655019
2014-07-31  0.942679  1.242009                        0.758995
2014-08-31  0.857444  1.449465                        0.591559
2014-09-30  0.770232  1.100339                        0.699995
2014-10-31  0.896812  1.304354                        0.687553
2014-11-30  1.105308  0.993083                        1.113007
2014-12-31  0.829460  1.025085                        0.809162
2015-01-31  0.736140  0.971904                        0.757421
2015-02-28  1.087115  1.114206                        0.975686
2015-03-31  0.980239  1.002017                        0.978267
2015-04-30  0.934329  0.922778                        1.012518
2015-05-31  1.017229  1.079724                        0.942119
2015-06-30  1.109809  1.019575                        1.088501
2015-07-31  1.105215  1.046731                        1.055873
2015-08-31  0.800393  1.162210                        0.688682
2015-09-30  1.034932  1.111078                        0.931467
2015-10-31  1.353321  1.052805                        1.285444
2015-11-30  1.154116  1.082976                        1.065689
2015-12-31  1.151178  1.388476                        0.829095
2016-01-31  0.887204  1.398100                        0.634578
...              ...       ...                             ...
2016-08-31  0.894966  1.100886                        0.812950
2016-09-30  1.051983  1.059128                        0.993254
2016-10-31  1.157340  1.210334                        0.956216
2016-11-30  1.051451  1.015322                        1.035585
2016-12-31  1.294330  1.198935                        1.079566
2017-01-31  0.976460  1.180387                        0.827236
2017-02-28  1.273606  1.144190                        1.113107
2017-03-31  0.886175  1.079164                        0.821168
2017-04-30  1.271178  1.126460                        1.128472
2017-05-31  1.675525  1.239496                        1.351779
2017-06-30  1.126202  0.947156                        1.189035
2017-07-31  1.090786  1.314527                        0.829793
2017-08-31  1.684943  1.099313                        1.532724
2017-09-30  0.916588  1.313127                        0.698019
2017-10-31  1.454930  1.162480                        1.251574
2017-11-30  1.631396  1.059009                        1.540494
2017-12-31  1.341707  1.319840                        1.016568
2018-01-31  0.772381  1.282527                        0.602234
2018-02-28  1.008095  1.275681                        0.790241
2018-03-31  0.672414  1.039425                        0.646910
2018-04-30  1.315830  1.169153                        1.125456
2018-05-31  0.803665  1.199528                        0.669984
2018-06-30  0.836180  1.040605                        0.803552
2018-07-31  1.279757  1.153691                        1.109272
2018-08-31  0.872673  1.161975                        0.751026
2018-09-30  0.945152  1.107776                        0.853198
2018-10-31  0.960498  1.009974                        0.951013
2018-11-30  0.654237  0.642605                        1.018101
2018-12-31  0.920142  1.209453                        0.760792
2019-01-31  0.906330  0.955699                        0.948342

[66 rows x 3 columns]

In [187]:
df_pct_change[:10]

               price  hashrate  price_change / hashrate_change
2013-08-31  1.271932  2.254223                        0.564244
2013-09-30  1.021847  1.864931                        0.547928
2013-10-31  1.584751  3.087456                        0.513287
2013-11-30  5.229783  1.476737                        3.541445
2013-12-31  0.739897  1.847970                        0.400384
2014-01-31  1.088564  1.824254                        0.596717
2014-02-28  0.692920  1.602777                        0.432325
2014-03-31  0.817087  1.328142                        0.615211
2014-04-30  0.953975  1.514007                        0.630099
2014-05-31  1.370002  1.285522                        1.065716

# Monthly Average Hashrate Change

In [188]:
np.average(df_pct_change['hashrate'].values)

1.231163101356691

In [189]:
np.average(df_pct_change['price'].values)

1.1187220932878617

# Hashrate Change Price Decreasing

In [192]:
np.average(df_pct_change.loc[(df_pct_change['price'] >= 1)]['hashrate'].values)

1.280772738534003

# Price Change Price Decreasing

In [193]:
np.average(df_pct_change.loc[(df_pct_change['price'] >= 1)]['price'].values)

1.3341633296704

# Monthly Average Price Change / Hashrate Change

In [194]:
np.average(df_pct_change['price_change / hashrate_change'])

0.9377588832525796

# Count Where Price Change Greater Than 1

In [195]:
df_pct_change['price_change > 1'] = df_pct_change['price'] > 1

In [196]:
sum(df_pct_change['price_change > 1'])

36

In [197]:
len(df_pct_change['price_change > 1'])

66

# Monthly Average Price Change / Hashrate Change .... where price change is positive

In [198]:
np.average(df_pct_change.loc[(df_pct_change['price'] >= 1)]['price_change / hashrate_change'].values)

1.08419774603064

# Monthly Average Price Change / Hashrate Change .... where price change is negative

In [199]:
np.average(df_pct_change.loc[(df_pct_change['price'] <= 1)]['price_change / hashrate_change'].values)

0.7620322479189078

# Weighted Average

In [200]:
((1.084*(36/66))+(.762*(30/66)))

0.9376363636363636

In [201]:
df_pct_change

,price,hashrate,price_change / hashrate_change,price_change > 1
2013-08-31,1.271932,2.254223,0.564244,True
2013-09-30,1.021847,1.864931,0.547928,True
2013-10-31,1.584751,3.087456,0.513287,True
2013-11-30,5.229783,1.476737,3.541445,True
2013-12-31,0.739897,1.847970,0.400384,False
2014-01-31,1.088564,1.824254,0.596717,True
2014-02-28,0.692920,1.602777,0.432325,False
2014-03-31,0.817087,1.328142,0.615211,False
2014-04-30,0.953975,1.514007,0.630099,False
2014-05-31,1.370002,1.285522,1.065716,True
2014-06-30,1.005209,1.534626,0.655019,True
2014-07-31,0.942679,1.242009,0.758995,False
2014-08-31,0.857444,1.449465,0.591559,False
2014-09-30,0.770232,1.100339,0.699995,False
2014-10-31,0.896812,1.304354,0.687553,False
2014-11-30,1.105308,0.993083,1.113007,True
2014-12-31,0.829460,1.025085,0.809162,False
2015-01-31,0.736140,0.971904,0.757421,False
2015-02-28,1.087115,1.114206,0.975686,True
2015-03-31,0.980239,1.002017,0.978267,False
2015-04-30,0.934329,0.922778,1.012518,False
2015-05-31,1.017229,1.079724,0.942119,True
2015-06-30,1.109809,1.019575,1.088501,True
2015-07-31,1.105215,1.046731,1.055873,True
2015-08-31,0.800393,1.162210,0.688682,False
2015-09-30,1.034932,1.111078,0.931467,True
2015-10-31,1.353321,1.052805,1.285444,True
2015-11-30,1.154116,1.082976,1.065689,True
2015-12-31,1.151178,1.388476,0.829095,True
2016-01-31,0.887204,1.398100,0.634578,False
...,...,...,...,...
2016-08-31,0.894966,1.100886,0.812950,False
2016-09-30,1.051983,1.059128,0.993254,True
2016-10-31,1.157340,1.210334,0.956216,True
2016-11-30,1.051451,1.015322,1.035585,True
2016-12-31,1.294330,1.198935,1.079566,True
2017-01-31,0.976460,1.180387,0.827236,False
2017-02-28,1.273606,1.144190,1.113107,True
2017-03-31,0.886175,1.079164,0.821168,False
2017-04-30,1.271178,1.126460,1.128472,True
2017-05-31,1.675525,1.239496,1.351779,True
2017-06-30,1.126202,0.947156,1.189035,True
2017-07-31,1.090786,1.314527,0.829793,True
2017-08-31,1.684943,1.099313,1.532724,True
2017-09-30,0.916588,1.313127,0.698019,False
2017-10-31,1.454930,1.162480,1.251574,True
2017-11-30,1.631396,1.059009,1.540494,True
2017-12-31,1.341707,1.319840,1.016568,True
2018-01-31,0.772381,1.282527,0.602234,False
2018-02-28,1.008095,1.275681,0.790241,True
2018-03-31,0.672414,1.039425,0.646910,False
2018-04-30,1.315830,1.169153,1.125456,True
2018-05-31,0.803665,1.199528,0.669984,False
2018-06-30,0.836180,1.040605,0.803552,False
2018-07-31,1.279757,1.153691,1.109272,True
2018-08-31,0.872673,1.161975,0.751026,False
2018-09-30,0.945152,1.107776,0.853198,False
2018-10-31,0.960498,1.009974,0.951013,False
2018-11-30,0.654237,0.642605,1.018101,False
2018-12-31,0.920142,1.209453,0.760792,False
2019-01-31,0.906330,0.955699,0.948342,False